config/routes.rb
Rails.application.routes.draw do

  root 'tops#index'

  resources :departments, only: [:index] do
    resources :posts, only: [:index]
  end

  resources :posts, only: [:create]

  resources :contacts, only: [:index]

  resources :public_relations, path: 'pr', only: [:index]

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :post
  belongs_to :faculty
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  has_many :department
end

app/models/post.rb
class Post < ActiveRecord::Base
   validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'flatly'

  before_action :login

  def login
    if session[:user_id].blank?
      user = User.create(name: [*1..9, *'A'..'Z', *'a'..'z'].sample(5).join)
      session[:user_id] = user.id
    end
    @user_id = session[:user_id]
    @user_name = User.where(id: @user_id).select(:name).pluck(:name)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @department_name = Department.find_by(id: params[:department_id]).name
    @posts = Post.where(department_id: params[:department_id])
                 .page(params[:page])
                 .per(10)
                 .order("id DESC")
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to department_posts_path params[:post][:department_id]
    else
      flash[:danger] = "書き込みに失敗しました。空では書き込みできません。"
      redirect_to department_posts_path params[:post][:department_id]
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :department_id, :session_id)
  end
end

app/controllers/public_relations_controller.rb
class PublicRelationsController < ApplicationController
  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @departments = Department.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "kit-c | 金沢工業大学の非公式掲示板"
    title = "kit-c"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{title}"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_relations_helper.rb
module PublicRelationsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/contacts/index.html.slim
- provide(:title, "お問い合わせ")

.row
  .col-lg-12
    .page-header
      h1.h2 お問い合わせなど

.row
  .col-lg-6
    .panel.panel-success
      .panel-heading
        h2.h4 お問い合わせ
      .panel-body
        | お問い合せは
        = link_to '@y_temp4', 'https://twitter.com/y_temp4'
        | までお願いします。

  .col-lg-6
    .panel.panel-info
      .panel-heading
        h2.h4 ソースコードはこちら
      .panel-body
        = link_to 'https://github.com/y-temp4/kit_c', 'https://github.com/y-temp4/kit_c'

.row
  .col-lg-12
    = link_to '>> 学科一覧へ', departments_path

app/views/departments/index.html.slim
- provide(:title, "学科一覧")

.row
  .col-lg-10.col-lg-offset-1
    .panel.panel-success
      .panel-heading
        h2.panel-title 学科一覧
      .panel-body
        ul.list-group
          - @departments.each do |department|
            li.list-group-item
              .list-content
                = link_to department.name, department_posts_path(department.id)
              span.badge
                = department.post.count

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title KitC
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

body

  = yield

app/views/layouts/flatly.html.slim
doctype 5
html(lang="ja")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= full_title(yield(:title))
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "flatly", :media => "all"
    = stylesheet_link_tag controller.controller_name , media: "all", "data-turbolinks-track" => true
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  body

  #wrap

    nav.navbar.navbar-default
      .container
        .container-fluid
          .navbar-header
            button(type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1")
              span.sr-only
              span.icon-bar
              span.icon-bar
              span.icon-bar
            = link_to 'kit-c', root_path, class: 'navbar-brand'

          .collapse.navbar-collapse#bs-example-navbar-collapse-1
            ul.nav.navbar-nav.navbar-right
              li
                  = link_to 'お問い合わせ', contacts_path
              li
                  = link_to 'PR', public_relations_path


    .container

      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")

      = yield

      #push

  footer.footer
    .container
      .text-center
        p
          small.h4 © kit-c

    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "flatly"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/posts/index.html.slim
- if params[:page]
  - provide(:title, "#{@department_name}の書き込み一覧 - #{params[:page]}ページ目")
- else
  - provide(:title, "#{@department_name}の書き込み一覧 - 1ページ目")

.post-container
  .row
    .col-lg-12
      h1.department-name
        = @department_name
    .col-lg-12
      .announce
        = link_to '>>学部一覧へ移動する', departments_path
    .col-lg-12
      = paginate @posts

  .row
    .col-lg-8.col-md-8.col-sm-8
      - if @posts.empty?
        .jumbotron
          h2 書き込みがありません！
          p あなたが書き込んで、最初の投稿者になろう！
      - else
        - @posts.each do |post|
            .panel.panel-default
              .panel-body
                .text-left
                  span id：
                  = post.session_id
              .panel-body.post-content
                  = post.content
              .panel-body
                .text-right
                  = post.created_at.to_s(:default)
    .col-lg-4.col-md-4.col-sm-4
      .form-to-footer
        = form_for Post.new do |f|
          .form-group
            = f.text_field :content, placeholder: 'テキストを入力してください', class: 'form-control set-form-width'
          = f.hidden_field :department_id, value: params[:department_id]
          = f.hidden_field :session_id, value: @user_name
          .text-right
            = f.submit value: '送信', class: 'btn btn-info set-btn-width'

  = paginate @posts

app/views/public_relations/index.html.slim
- provide(:title, "PR")

.row
  .col-lg-12
    .page-header
      h1.h2 ちょっとした宣伝

  .col-lg-6.col-md-6
    .panel.panel-info
      .panel-heading
        h2.h4 電子計算機研究会
      .panel-body
        blockquote.club-info
          p
            |
              電子計算機研究会とは、 パソコンを使って制作活動をする部活です。 制作活動といっても色々ありますが、主に
          ul
            li PROGRAMMING(プログラミング)
            li CG(コンピュータグラフィック)
            li DTM(デスクトップミュージック)
            li NETWORK(ネットワーク)
          p
            |
              の制作活動をしています。
          small 下記サイトより引用

        ul
          li
            | サイト
            ul
              li
                = link_to 'http://www2.kanazawa-it.ac.jp/kitic/', 'http://www2.kanazawa-it.ac.jp/kitic/'
          li
            | Twitter
            ul
              li
                = link_to '@kitic', 'https://twitter.com/kitic_densan'

  .col-lg-6.col-md-6
    .panel.panel-cirkit
      .panel-heading
        h2.h4 CirKit
      .panel-body
        .well
          |
            ざっくり言うと、CirKitはITを駆使した地域活性化に取り組む団体です。
            下のサイトは金沢工業大学周辺のお店を集めたポータルサイトです。
            地元に詳しくない人は参考にしてね。

        ul
          li
            | サイト
            ul
              li
                = link_to 'http://www.cirkit.jp/', 'http://www.cirkit.jp/'
          li
            | Twitter
            ul
              li
                | 株式会社CirKit
                ul
                  li
                    = link_to '@cirkit_co', 'https://twitter.com/cirkit_co'
              li
                | CirKitポータル（公式）
                ul
                  li
                    = link_to '@CirKit_Portal', 'https://twitter.com/CirKit_Portal'

  .col-lg-12.col-md-12
    .alert.alert-danger.alert-dismissible
      button(type="button" class="close" data-dismiss="alert")×
      h4 どちらも絶賛メンバー募集中です！
      p
        | 詳しくは下記のリンク、もしくは
        = link_to '@y_temp4', 'https://twitter.com/y_temp4', class: 'alert-link'
        | に連絡していただけたら、直接対応します。

.row
  .col-lg-12
    = link_to '>> 学科一覧へ', departments_path

app/views/tops/index.html.slim
.jumbotron
  h1 KIT非公認掲示板（仮）
  p このサイトは非公式で運営している、金沢工業大学の掲示板っぽいものです。

.row
  .col-lg-10.col-lg-offset-1
    .panel.panel-info
      .panel-heading
        h2.panel-title 使い方
      .panel-body
        ol
          li 学科を選択しましょう。
          li ページが移動するので、書き込み、もしくはROMりましょう。

.row
  .col-lg-10.col-lg-offset-1
    .panel.panel-success
      .panel-heading
        h2.panel-title 学科一覧
      .panel-body
        ul.list-group
          - @departments.each do |department|
            li.list-group-item
              .list-content
                = link_to department.name, department_posts_path(department.id)
              span.badge
                = department.post.count